### PR TITLE
added vertical scrolling

### PR DESCRIPTION
**Pull request by PatrickSBradley**
I need to be able to vertically scroll in the project I am working on.  I added a switch to the main page so the user could switch between horizontal and vertical scrolling.

Chris,

I added xam.plugins.settings nuget package to the project to get the switch settings to persist.

The following files were changed to get the vertical stuff working:
carousellayout.cs, homepage.cs, switcherpage.cs, droid version of carouselrenderer.cs

Hope this is helpful to your project!

Pat Bradley

### CODE REVIEW

**Comment by PatrickSBradley** [comment]
Chris, I realized using the plug in for settings will probably not be acceptable for a pull request(plus it is really a hammer approach and not necessary).  So, I am going to make adjustments in the code to not use the plugin.  I am going to close this pull request and resubmit another in a few days.  I am hoping to continue to contribute to your project in the future, because I am planning to use your project as the base in a larger project I am involved in.

**Comment by chrisriesgo** [comment]
Thanks @PatrickSBradley! I appreciate you taking the time to contribute. I'm curious -- which version of Xamarin.Forms are you running?

**Comment by PatrickSBradley** [comment]
When I look at the CustomLayouts.sln that I forked from your repository, the references for Xamarin.Forms.Core and Xamarin.Forms.Xaml have a runtime version of v4.030319.  Xamarin.Forms.Platform\* have v2.0.50727.  The larger project I am involved in will use whatever is the latest version,We are just switching over to Xamarin.Forms(we had the ios pretty much coded and were ready to do the android version and decided to make the switch now to Xamarin.Forms).

**Comment by PatrickSBradley** [comment]
on another note, we noticed about 3 warnings of deprecated stuff when we plugged your stuff in... i will submit a fix for that as pull request for that soon.

**Pull request closed without merging**
